# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: './gradlew'
      options: '-Penv=authoring'
      tasks: 'bundle'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: '4f61c9be-a827-4ffd-b406-9e3290fc4b49'
      pipeline: '1'
      buildVersionToDownload: 'latest'
      downloadType: 'specific'
      itemPattern: 'bundles/crafter-cms-authoring.tar.gz'
      downloadPath: '$(System.ArtifactsDirectory)'
